name: Terraform Apply

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.tf'
      - 'modules/**'
      - '!next/**'

jobs:
  apply:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TF_VAR_domain_root: ${{ secrets.TF_DOMAIN_ROOT }}
      TF_VAR_domain_www: ${{ secrets.TF_DOMAIN_WWW }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.TF_CLOUDFLARE_ZONE_ID }}
      TF_VAR_bucket_name: ${{ secrets.TF_BUCKET_NAME }}
      TF_VAR_index_html_content: ${{ secrets.TF_INDEX_HTML || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
